include: package:lint/analysis_options.yaml

analyzer:
  exclude:
    - lib/generated/*.dart
    - lib/generated/intl/messages_en.dart
    - lib/**/*.g.dart

linter:
  rules:
    avoid_classes_with_only_static_members: false